checks for dependencies in flatcar-install script
flatcar-linux/init pull request #50
Opened 2021-09-06 21:32 UTC by ArkaprabhaChakraborty

#added checks for dependencies in the flatcar-install script
the flatcar-install script didn't check if the required dependencies are there in the system or not. The following checks make sure the required dependencies are installed before running flatcar-install.

2021-09-07 06:10 UTC, krnowak requested changes

2021-09-07 06:10 UTC, krnowak commented on bin/flatcar-install
> +    command -v bzip2 > /dev/null || { echo "error: command 'bzip2' not found" > /dev/stderr ; exit 1 ; }
You could put it in the `else` clause above. Then the `flag` variable will not be needed.

2021-09-07 06:10 UTC, krnowak commented on bin/flatcar-install
> +command -v wget > /dev/null || { echo "error: command 'wget' not found" > /dev/stderr ; exit 1 ; }
To avoid repetition, you could write a function and invoke it in a for loop. Also please sort the tools alphabetically.

```bash
ensure_tool() {
    local tool="${1}"
    if ! command -v "${tool}"; then
        echo "error: command '${tool}' not found" >&2
        exit 1
    fi
}

tools=(
    cp
    dd
    …
)

for t in "${tools[@]}"; do ensure_tool "${t}"; done
```

Also, note that typical way to redirect to stderr is to do `>&2`.

One more thing, there are a couple tools missing from the list:
```
blockdev
btrfstune
cut
gawk
head
mktemp
sed
sort
udevadm
wipefs
```

2021-09-07 06:10 UTC, krnowak commented on bin/flatcar-install
> +command -v gpg2 > /dev/null || {echo "error: command 'gpg2' not found" > /dev/stderr ; exit 1 ; }
I think gpg2 appears only in a comment - it not necessary for the script to work.

2021-09-07 06:10 UTC, krnowak commented on bin/flatcar-install
> +command -v gpg > /dev/null || {echo "error: command 'gpg' not found" > /dev/stderr ; exit 1 ; }
There are checks for `gpg` and `wget` in the `prep_url` function, you could drop those if you are checking them here.

2021-09-07 06:53 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +    command -v bzip2 > /dev/null || { echo "error: command 'bzip2' not found" > /dev/stderr ; exit 1 ; }
yes that would be better for the script.

2021-09-07 06:55 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +command -v wget > /dev/null || { echo "error: command 'wget' not found" > /dev/stderr ; exit 1 ; }
Yes I will do that. I'm actually beginner in shell scripting and I took this up thinking it would help me learn more about it. Thanks for the help !

2021-09-07 08:30 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +command -v gpg2 > /dev/null || {echo "error: command 'gpg2' not found" > /dev/stderr ; exit 1 ; }
Okay got it.

2021-09-07 08:36 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +command -v gpg > /dev/null || {echo "error: command 'gpg' not found" > /dev/stderr ; exit 1 ; }
Since its being checked by a function already, it's not required then.

2021-09-08 18:35 UTC, ArkaprabhaChakraborty commented
I have made the required changes.

2021-09-09 19:01 UTC, krnowak requested changes
Hi, thanks for the update! There are still some changes required, though.

2021-09-09 19:01 UTC, krnowak commented on bin/flatcar-install
> +    command -v bzip2 > /dev/null || { echo "error: command 'bzip2' not found" > /dev/stderr ; exit 1 ; }
You could move the `ensure_tool` definition to be right after the `set -e -o pipefail`, so you could invoke it here too.

2021-09-09 19:01 UTC, krnowak commented on bin/flatcar-install
> +    lsblk, mkdir, mkfifo, mktemp, mount, rm, sed, tee, udevadm, wipefs)
`gpg`, `sort` and `wget` are still missing here. I know that `gpg` and `wget` are checked below in the `prep_url` function, so I'd like you to remove the checks from the function. That way we keep all the tool checks in one place. Thanks!

2021-09-09 19:01 UTC, krnowak commented on bin/flatcar-install
> +command -v gpg2 > /dev/null || {echo "error: command 'gpg2' not found" > /dev/stderr ; exit 1 ; }
These lines can be dropped now.

2021-09-09 19:06 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +    command -v bzip2 > /dev/null || { echo "error: command 'bzip2' not found" > /dev/stderr ; exit 1 ; }
Okay will do that

2021-09-09 19:08 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +    lsblk, mkdir, mkfifo, mktemp, mount, rm, sed, tee, udevadm, wipefs)
Okay got it. I thought it's being checked b in the prep_url function so I didn't do it again. I will move it to the ensure_tool checking block.

2021-09-09 19:21 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +command -v gpg2 > /dev/null || {echo "error: command 'gpg2' not found" > /dev/stderr ; exit 1 ; }
I forgot to push this commit. Sorry.

2021-09-09 22:10 UTC, ArkaprabhaChakraborty commented
I have made the necessary changes. But while using the script from my fork, I get this error: 
`gpg: invalid armor header: mQINBFqUFawBEACdnSVBBSx3negnGv7Ppf2D6fbIQAHSzUQ+BA5zEG02BS6EKbJh\n
Error: return code 2 from gpg --batch --quiet --import <<< "${GPG_KEY} `

2021-09-10 06:47 UTC, krnowak requested changes
One minor thing is left, otherwise it will be good to go.

After fixing it, could you squash the commits?

2021-09-10 06:47 UTC, krnowak commented on bin/flatcar-install
> +trap - EXIT
Looks like you removed the newline here in commit f4dd2f36e52864f5b0f458ba74bd7b5dc063cea0. Could you bring this back? Thanks!

2021-09-10 06:51 UTC, krnowak commented
> I have made the necessary changes. But while using the script from my fork, I get this error:
> `gpg: invalid armor header: mQINBFqUFawBEACdnSVBBSx3negnGv7Ppf2D6fbIQAHSzUQ+BA5zEG02BS6EKbJh\n Error: return code 2 from gpg --batch --quiet --import <<< "${GPG_KEY} `

Hmm, this isn't related in any way to your changes, so this issue won't block this PR. Thanks for spotting it.

2021-09-10 07:27 UTC, krnowak commented
> I have made the necessary changes. But while using the script from my fork, I get this error:
> `gpg: invalid armor header: mQINBFqUFawBEACdnSVBBSx3negnGv7Ppf2D6fbIQAHSzUQ+BA5zEG02BS6EKbJh\n Error: return code 2 from gpg --batch --quiet --import <<< "${GPG_KEY} `

Did you get [this empty line](https://github.com/kinvolk/init/blob/82c6f3c45411e1d9254fb664f14ece39cdbf2f54/bin/flatcar-install#L120) removed by accident? This will cause gpg to complain about the invalid header. And it's really easy to trigger it, if you copy the GPG_KEY variable from github and paste it somewhere else - happened to me too.

2021-09-10 08:52 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +trap - EXIT
Ill bring it back.

2021-09-10 09:27 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +trap - EXIT
> > I have made the necessary changes. But while using the script from my fork, I get this error:
> > `gpg: invalid armor header: mQINBFqUFawBEACdnSVBBSx3negnGv7Ppf2D6fbIQAHSzUQ+BA5zEG02BS6EKbJh\n Error: return code 2 from gpg --batch --quiet --import <<< "${GPG_KEY} `
> 
> Did you get [this empty line](https://github.com/kinvolk/init/blob/82c6f3c45411e1d9254fb664f14ece39cdbf2f54/bin/flatcar-install#L120) removed by accident? This will cause gpg to complain about the invalid header. And it's really easy to trigger it, if you copy the GPG_KEY variable from github and paste it somewhere else - happened to me too.

No, I didn't. It's still there.

2021-09-10 09:28 UTC, ArkaprabhaChakraborty commented
> > I have made the necessary changes. But while using the script from my fork, I get this error:
> > `gpg: invalid armor header: mQINBFqUFawBEACdnSVBBSx3negnGv7Ppf2D6fbIQAHSzUQ+BA5zEG02BS6EKbJh\n Error: return code 2 from gpg --batch --quiet --import <<< "${GPG_KEY} `
> 
> Did you get [this empty line](https://github.com/kinvolk/init/blob/82c6f3c45411e1d9254fb664f14ece39cdbf2f54/bin/flatcar-install#L120) removed by accident? This will cause gpg to complain about the invalid header. And it's really easy to trigger it, if you copy the GPG_KEY variable from github and paste it somewhere else - happened to me too.

No, I didn't. That Line is still there.

2021-09-10 09:30 UTC, ArkaprabhaChakraborty commented on bin/flatcar-install
> +trap - EXIT
There was a space after EXIT. Do you mean that space?

2021-09-10 10:24 UTC, ArkaprabhaChakraborty commented
Squashed them to 5 commits. Should I squash them even more?

2021-09-10 11:09 UTC, krnowak commented
> Squashed them to 5 commits. Should I squash them even more?

Squashing it to one commit for this PR should be fine.

2021-09-10 11:11 UTC, krnowak commented
> > > I have made the necessary changes. But while using the script from my fork, I get this error:
> > > `gpg: invalid armor header: mQINBFqUFawBEACdnSVBBSx3negnGv7Ppf2D6fbIQAHSzUQ+BA5zEG02BS6EKbJh\n Error: return code 2 from gpg --batch --quiet --import <<< "${GPG_KEY} `
> > 
> > 
> > Did you get [this empty line](https://github.com/kinvolk/init/blob/82c6f3c45411e1d9254fb664f14ece39cdbf2f54/bin/flatcar-install#L120) removed by accident? This will cause gpg to complain about the invalid header. And it's really easy to trigger it, if you copy the GPG_KEY variable from github and paste it somewhere else - happened to me too.
> 
> No, I didn't. That Line is still there.

Curious. Please [file an issue](https://github.com/kinvolk/Flatcar/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.md&title=) about it then. Please add the information about how did you invoke the script to generate the error and what is the output of `gpg --version`. Thanks!

2021-09-10 11:12 UTC, krnowak commented on bin/flatcar-install
> +trap - EXIT
Nah, the space could be dropped. :) I only meant to bring back the newline.

2021-09-10 11:54 UTC, ArkaprabhaChakraborty commented
The script works fine now. I tested the script again and now it works fine. I dont know what caused the error but it didn't trigger again. 🙂

2021-09-10 12:24 UTC, krnowak commented
> The script works fine now. I tested the script again and now it works fine. I dont know what caused the error but it didn't trigger again. slightly_smiling_face

Heh, alright. :) If this happens, feel free to file the issue anyway.

2021-09-10 12:24 UTC, krnowak approved these changes
Let's get this in.

2021-09-10 12:25 UTC, merged

2021-09-10 12:25 UTC, krnowak commented
Thanks for the PR!