Added option to specify port1 and port2
flatcar-linux/init pull request #81
Opened 2022-08-25 10:25 UTC by karstenjakobsen

# [Title: describe the change in one sentence]

Added option to specify port1 and port2

new params

"  -L, --listen-port-1 <LISTEN_PORT_1> Overwrites standard listen port 9090"
"  -M, --listen-port-2 <LISTEN_PORT_2> Overwrites standard listen port 9091"

## How to use

Test by using

```
flatcar-update --to-version 3227.2.2 --listen-port-1 8091 --listen-port-2 8092
```

## Testing done

Tested in flatcar 3227.2.0

2022-08-25 14:39 UTC, krnowak requested changes
Thanks for the PR! Found some small issues.

2022-08-25 14:39 UTC, krnowak commented on bin/flatcar-update
>  opts=$(getopt --name "$(basename "${0}")" --options 'hV:P:DFA' \
Short options are missing:

```suggestion
opts=$(getopt --name "$(basename "${0}")" --options 'hV:P:L:M:DFA' \
```

2022-08-25 14:39 UTC, krnowak commented on bin/flatcar-update
> +    echo "  -M, --listen-port-2 <LISTEN_PORT_2> Overwrites standard listen port 9091"
Just PORT should be enough:
```suggestion
    echo "  -L, --listen-port-1 <PORT> Overwrites standard listen port 9090"
    echo "  -M, --listen-port-2 <PORT> Overwrites standard listen port 9091"
```

2022-08-25 14:39 UTC, krnowak commented on bin/flatcar-update
> +    echo "Usage: $(basename "${0}") --to-version VERSION [--to-payload FILENAME] [--listen-port-1 LISTEN_PORT_1] [--listen-port-2 LISTEN_PORT_2] [--force-dev-key|--force-flatcar-key|--disable-afterwa
Just PORT should be enough - it describes what kind of parameter this should be (so not a number greater than 65535, for instance).

```suggestion
    echo "Usage: $(basename "${0}") --to-version VERSION [--to-payload FILENAME] [--listen-port-1 PORT] [--listen-port-2 PORT] [--force-dev-key|--force-flatcar-key|--disable-afterwards|]"
```

2022-08-25 21:20 UTC, pothos commented on bin/flatcar-update
> +ncat --keep-open -c "echo -en 'HTTP/1.1 200 OK\ncontent-type: text/xml\ncontent-length: $(stat --printf='%s\n' /tmp/response)\n\n'; cat /tmp/response" -l $LISTEN_PORT_1 &
```suggestion
ncat --keep-open -c "echo -en 'HTTP/1.1 200 OK\ncontent-type: application/gzip\ncontent-length: $SIZE\n\n'; cat \"$PAYLOAD\"" -l "$LISTEN_PORT_2" &
ncat --keep-open -c "echo -en 'HTTP/1.1 200 OK\ncontent-type: text/xml\ncontent-length: $(stat --printf='%s\n' /tmp/response)\n\n'; cat /tmp/response" -l "$LISTEN_PORT_1" &
```
Quoting to have a proper error message from ncat if the port variable is empty or contains whitespace

2022-08-29 09:23 UTC, karstenjakobsen commented
Suggested changes are committed :)

2022-08-30 08:36 UTC, krnowak approved these changes
Two nitpicks, otherwise looks good.

2022-08-30 08:36 UTC, krnowak commented on bin/flatcar-update
> +    echo "Usage: $(basename "${0}") --to-version VERSION [--to-payload FILENAME] [--listen-port-1 PORT] [--listen-port-2 PORT] [--force-dev-key|--force-flatcar-key|--disable-afterwards|]"
```suggestion
    echo "Usage: $(basename "${0}") --to-version VERSION [--to-payload FILENAME] [--listen-port-1 PORT] [--listen-port-2 PORT] [--force-dev-key|--force-flatcar-key|--disable-afterwards]"
```

2022-08-30 08:36 UTC, krnowak commented on bin/flatcar-update
> +    echo "  -M, --listen-port-2 <PORT> Overwrites standard listen port 9091"
Let's align those lines back.

```suggestion
    echo "  -V, --to-version <VERSION>	Updates to the version, by default using the matching release from update.release.flatcar-linux.net"
    echo "  -P, --to-payload <FILENAME>	Updates to the given update payload file instead of downloading it"
    echo "  -D, --force-dev-key		Bind-mounts the dev key over /usr/share/update_engine/update-payload-key.pub.pem"
    echo "  -F, --force-flatcar-key	Bind-mounts the Flatcar release key over /usr/share/update_engine/update-payload-key.pub.pem"
    echo "  -A, --disable-afterwards	Writes SERVER=disabled to /etc/flatcar/update.conf when done (this overwrites any custom SERVER)"
    echo "  -L, --listen-port-1 <PORT>  Overwrites standard listen port 9090"
    echo "  -M, --listen-port-2 <PORT>  Overwrites standard listen port 9091"
```

2022-10-03 09:00 UTC, karstenjakobsen commented
> Two nitpicks, otherwise looks good.

Fixed - thank you

2022-10-04 08:37 UTC, krnowak approved these changes

2022-10-04 08:39 UTC, merged

2022-10-04 08:39 UTC, krnowak commented
Thanks again for the PR!

2022-10-04 13:33 UTC, krnowak commented
PR in coreos-overlay to pull these changes for the next alpha: https://github.com/flatcar/coreos-overlay/pull/2198